toolsets:
  kubernetes/core:
    enabled: false

  kubernetes/logs:
    enabled: false

  internet:
    enabled: false

  grafana/loki:
    enabled: true
    config:
      url: "http://grafana:3000"
      api_key: "" # Grafana API key
      grafana_datasource_uid: "" # Grafana datasource uid


