# GoReleaser configuration
# https://goreleaser.com/customization/

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: alertsnitch
    main: ./main.go
    binary: alertsnitch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X gitlab.com/yakshaving.art/alertsnitch/version.Version={{.Version}}
      - -X gitlab.com/yakshaving.art/alertsnitch/version.Commit={{.Commit}}
      - -X gitlab.com/yakshaving.art/alertsnitch/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - db.d/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: '🚀 Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: '⚡ Performance'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: '📚 Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: '🔧 Others'
      order: 999

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: alertsnitch
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## AlertSnitch {{ .Version }}

    Alert history storage for Prometheus Alertmanager.
  footer: |
    ---
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap (optional, enable if you have a homebrew-tap repo)
# brews:
#   - repository:
#       owner: MikeHsu0618
#       name: homebrew-tap
#     folder: Formula
#     homepage: https://github.com/MikeHsu0618/alertsnitch
#     description: Alert history storage for Prometheus Alertmanager
#     license: MIT

