# docker-compose --profile loki up
# docker-compose --profile mysql up

version: '3.7'

services:
  alertsnitch:
    image: mikehsu0618/alertsnitch:latest
    ports:
      - "9567:9567"
    env_file:
      - .env
    environment:
      ALERTSNITCH_DEBUG: true
      ALERTSNITCH_BACKEND_ENPOINT: "${ALERTSNITCH_BACKEND_ENPOINT}"
      ALERTSNITCH_BACKEND: "${ALERTSNITCH_BACKEND}"
      ALERTSNITCH_LOKI_TENANT_ID: "${ALERTSNITCH_LOKI_TENANT_ID}"
      ALERTSNITCH_LOKI_BASIC_AUTH_USER: "${ALERTSNITCH_LOKI_BASIC_AUTH_USER}"
      ALERTSNITCH_LOKI_BASIC_AUTH_PASSWORD: "${ALERTSNITCH_LOKI_BASIC_AUTH_PASSWORD}"
    depends_on:
      - "${ALERTSNITCH_BACKEND}"
    profiles:
      - loki
      - mysql 

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
    profiles:
      - loki 

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./configs:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    profiles:
      - loki
      - mysql

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    profiles:
      - loki

  mysqldb:
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db.d/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: alertsnitch
      MYSQL_USER: "alertsnitch"
      MYSQL_PASSWORD: "alertsnitch"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      timeout: 20s
      retries: 10
    profiles:
      - mysql 