# docker-compose --profile loki up
# docker-compose --profile mysql up

version: '3.7'

services:
  # alertsnitch:
  #   image: registry.gitlab.com/yakshaving.art/alertsnitch:0.2
  #   ports:
  #     - "9567:9567"
  #   environment:
  #     ALERTSNITCH_BACKEND_ENPOINT: ${ALERTSNITCH_BACKEND_ENDPOINT}
  #     ALERTSNITCH_BACKEND: ${ALERTSNITCH_BACKEND}
  #   depends_on:
  #     - ${ALERTSNITCH_BACKEND}
  #   profiles:
  #     - loki
  #     - mysql 

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    profiles:
      - loki  # 只會在 loki profile 啟動時啟動

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./configs:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    profiles:
      - loki
      - mysql

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    profiles:
      - loki

  mysqldb:
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db.d/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: alertsnitch
      MYSQL_USER: "alertsnitch"
      MYSQL_PASSWORD: "alertsnitch"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      timeout: 20s
      retries: 10
    profiles:
      - mysql 