{
 "title": "prometheus alert history",
 "description": "Dashboard for alertsnitch。https://gitlab.com/yakshaving.art/alertsnitch",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "total number of alert sended",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(1)\nFROM Alert\nWHERE\n  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n  AND status=\"firing\""
    }
   ]
  },
  {
   "title": "alert statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  startsAt AS time,\n  status,\n  ID\nFROM Alert\nWHERE\n  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n  AND status=\"firing\"\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"severity\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t  AND status=\"firing\"\n\t)\n\tAND lkv.LabelKey=\"severity\""
    }
   ]
  },
  {
   "title": "total number of alert resolved",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(1)\nFROM Alert\nWHERE\n  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n  AND status=\"resolved\""
    }
   ]
  },
  {
   "title": "resolved statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  startsAt AS time,\n  status,\n  ID\nFROM Alert\nWHERE\n  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n  AND status=\"resolved\"\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"severity\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t  AND status=\"resolved\"\n\t)\n\tAND lkv.LabelKey=\"severity\""
    }
   ]
  },
  {
   "title": "alert triggered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  startsAt AS time,\n  ID\nFROM Alert\nWHERE\n  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n  AND status=\"firing\"\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "resolved triggered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  startsAt AS time,\n  ID\nFROM Alert\nWHERE\n  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n  AND status=\"resolved\"\nORDER BY startsAt"
    }
   ]
  },
  {
   "title": "alert not resolved",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  ID,\n  status,\n  startsAt,\n  endsAt,\n  TIMESTAMPDIFF(SECOND, startsAt, UTC_TIMESTAMP()) AS duration,\n  fingerprint\nFROM Alert\nWHERE\n  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\nORDER BY ID"
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"alertname\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"alertname\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"env\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"env\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"severity\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"severity\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"az\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"az\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"hostname\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"hostname\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"project\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"project\""
    },
    {
     "rawSql": "SELECT\n\taa.AlertID AS \"ID\",\n\takv.Value AS \"description\"\nFROM\n\tAlertAnnotation aa\n\tINNER JOIN AnnotationKV akv ON aa.AnnotationKVID = akv.ID\nWHERE\n\taa.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND akv.AnnotationKey=\"description\""
    }
   ]
  },
  {
   "title": "alert resolved",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  ID,\n  status,\n  startsAt,\n  endsAt,\n  TIMESTAMPDIFF(SECOND, startsAt, endsAt) AS duration,\n  fingerprint\nFROM Alert\nWHERE\n  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n  AND status=\"resolved\"\nORDER BY startsAt"
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"alertname\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t  AND status=\"resolved\"\n\t)\n\tAND lkv.LabelKey=\"alertname\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"env\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t  AND status=\"resolved\"\n\t)\n\tAND lkv.LabelKey=\"env\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"severity\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t  AND status=\"resolved\"\n\t)\n\tAND lkv.LabelKey=\"severity\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"az\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t  AND status=\"resolved\"\n\t)\n\tAND lkv.LabelKey=\"az\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"hostname\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t  AND status=\"resolved\"\n\t)\n\tAND lkv.LabelKey=\"hostname\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"project\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t  AND status=\"resolved\"\n\t)\n\tAND lkv.LabelKey=\"project\""
    },
    {
     "rawSql": "SELECT\n\taa.AlertID AS \"ID\",\n\takv.Value AS \"description\"\nFROM\n\tAlertAnnotation aa\n\tINNER JOIN AnnotationKV akv ON aa.AnnotationKVID = akv.ID\nWHERE\n\taa.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t  AND status=\"resolved\"\n\t)\n\tAND akv.AnnotationKey=\"description\""
    }
   ]
  },
  { "title": "alert details query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "history alert details",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  ID,\n  status,\n  startsAt,\n  endsAt,\n  fingerprint\nFROM Alert\nWHERE\n  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\nORDER BY ID"
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"alertname\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"alertname\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"env\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"env\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"severity\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"severity\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"az\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"az\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"hostname\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"hostname\""
    },
    {
     "rawSql": "SELECT\n\tal.AlertID AS \"ID\",\n\tlkv.Value AS \"project\"\nFROM\n\tAlertLabel al\n\tINNER JOIN LabelKV lkv ON al.LabelKVID = lkv.ID\nWHERE\n\tal.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND lkv.LabelKey=\"project\""
    },
    {
     "rawSql": "SELECT\n\taa.AlertID AS \"ID\",\n\takv.Value AS \"description\"\nFROM\n\tAlertAnnotation aa\n\tINNER JOIN AnnotationKV akv ON aa.AnnotationKVID = akv.ID\nWHERE\n\taa.AlertID IN (\n\tSELECT\n\t\tID \n\tFROM\n\t\tAlert \n\tWHERE\n\t  startsAt BETWEEN DATE_SUB(FROM_UNIXTIME(${__from:date:seconds}),INTERVAL 8 HOUR) AND DATE_SUB(FROM_UNIXTIME(${__to:date:seconds}),INTERVAL 8 HOUR)\n\t)\n\tAND akv.AnnotationKey=\"description\""
    }
   ]
  }
 ]
}