fullnameOverride: loki
deploymentMode: Distributed

loki:
  limits_config:
    max_query_series: 100000

write:
  replicas: 0
backend:
  replicas: 0
read:
  replicas: 0

compactor:
  replicas: 1

distributor:
  replicas: 1



gateway:
  enabled: true
  replicas: 1
indexGateway:
  maxUnavailable: 1
  replicas: 1
ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false

bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

minio:
  enabled: true

patternIngester:
  replicas: 0

querier:
  replicas: 1

queryFrontend:
  replicas: 1

queryScheduler:
  enabled: true
  replicas: 1

memcachedExporter:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

rollout_operator:
  enabled: false

ruler:
  enabled: false
  replicas: 1

lokiCanary:
  enabled: false
  push: false

test:
  enabled: false

monitoring:
  dashboards:
    enabled: ture
  serviceMonitor:
    enabled: true
